# V3/incidences/sources.yaml
sources:
  ci5_ix:
    type: "online"
    description: "Cancer Incidence in Five Continents IX (1998-2002)"
    url: "https://gco.iarc.fr/media/ci5/data/ci5-ix/old/vol9/CI5-IXd.zip"
    cohort: "1998-2002"
    parser: "ci5_detailed_incidence_model"
    data_dir: "ci5_ix"
    format: "zip"
    default_population: "38402499"
    has_header: false
    age_structure:
      age_groups:
        - min: 0
          max: 4
        - min: 5
          max: 9
        - min: 10
          max: 14
        - min: 15
          max: 19
        - min: 20
          max: 24
        - min: 25
          max: 29
        - min: 30
          max: 34
        - min: 35
          max: 39
        - min: 40
          max: 44
        - min: 45
          max: 49
        - min: 50
          max: 54
        - min: 55
          max: 59
        - min: 60
          max: 64
        - min: 65
          max: 69
        - min: 70
          max: 74
        - min: 75
          max: 79
        - min: 80
          max: 84
        - min: 85
          max: null  # open-ended age class
        - min: null
          max: null  # class for unknown age
      unknown_age_class: 19
      open_ended_age_class: 18
    population_mappings:
      - population_id: 10120199
        cool_label: Algeria
        description: Algeria
      - population_id: 17160270
        cool_label: Zimbabwe
        description: Zimbabwe
      - population_id: 18000299
        cool_label: Uganda
        description: Uganda
      - population_id: 20320199
        cool_label: Argentina
        description: Argentina
      - population_id: 20760899
        cool_label: Brazil
        description: "*Brazil (Sao Paolo)"
      - population_id: 21700199
        cool_label: Colombia
        description: Colombia
      - population_id: 21880099
        cool_label: CostaRica
        description: CostaRica
      - population_id: 22180199
        cool_label: Ecuador
        description: Ecuador
      - population_id: 31240099
        cool_label: Canada
        description: Canada
      - population_id: 38400942
        cool_label: US_Natives
        description: "*USA, New Mexico: American Indian"
      - population_id: 38402450
        cool_label: US_Hispanic
        description: "*USA, SEER (14 Registries): Hispanic White"
      - population_id: 38402429
        cool_label: US_Asian
        description: "*USA, SEER (14 Registries): Asian and Pacific Islander"
      - population_id: 38402010
        cool_label: US_White
        description: "*USA, SEER (9 Registries): White"
      - population_id: 38402030
        cool_label: US_Black
        description: "*USA, SEER (9 Registries): Black"
      - population_id: 41560399
        cool_label: China
        description: "*China, Shanghai"
      - population_id: 43560399
        cool_label: India
        description: "*India, Mumbai (Bombay)"
      - population_id: 43760090
        cool_label: Israel_Jews
        description: "Israel: Jews"
      - population_id: 43760099
        cool_label: Israel
        description: "Israel: Non-Jews"
      - population_id: 43920299
        cool_label: Japan
        description: "*Japan, Miyagi Prefecture"
      - population_id: 44100099
        cool_label: Korea
        description: Korea
      - population_id: 44140025
        cool_label: Kuwait
        description: "*Kuwait: Kuwaitis"
      - population_id: 46080299
        cool_label: Philippines
        description: Philippines
      - population_id: 47640199
        cool_label: Thailand
        description: "*Thailand, Chiang Mai"
      - population_id: 50400099
        cool_label: Austria
        description: Austria
      - population_id: 50560499
        cool_label: Belgium
        description: "*Belgium, Antwerp*"
      - population_id: 51120099
        cool_label: Belarus
        description: Belarus
      - population_id: 51910099
        cool_label: Croatia
        description: Croatia
      - population_id: 52030099
        cool_label: Czech
        description: "Czech Republic"
      - population_id: 52080099
        cool_label: Denmark
        description: Denmark
      - population_id: 52330099
        cool_label: Estonia
        description: Estonia
      - population_id: 52500199
        cool_label: France
        description: "*France, Bas-Rhin"
      - population_id: 52760299
        cool_label: Germany
        description: "*Germany, Hamburg"
      - population_id: 53520099
        cool_label: Iceland
        description: Iceland
      - population_id: 53720099
        cool_label: Ireland
        description: Ireland
      - population_id: 53800199
        cool_label: Italy
        description: "*Italy, Florence and Prato"
      - population_id: 54280099
        cool_label: Latvia
        description: Latvia
      - population_id: 54400099
        cool_label: Lithuania
        description: Lithuania
      - population_id: 54700099
        cool_label: Malta
        description: Malta
      - population_id: 55280099
        cool_label: Netherlands
        description: Netherlands
      - population_id: 55780099
        cool_label: Norway
        description: Norway
      - population_id: 56160199
        cool_label: Poland
        description: "*Poland, Cracow"
      - population_id: 56200499
        cool_label: Portugal
        description: "*Portugal, Porto"
      - population_id: 57050099
        cool_label: Slovenia
        description: Slovenia
      - population_id: 57240299
        cool_label: Spain
        description: "*Spain, Granada"
      - population_id: 57560299
        cool_label: Switzerland
        description: "*Switzerland, Geneva"
      - population_id: 57920299
        cool_label: Turkey
        description: "*Turkey, Antalya"
      - population_id: 58260699
        cool_label: UK
        description: "*UK, England, South and Western Regions"
      - population_id: 60360499
        cool_label: Australia
        description: "*Australia, South"
      - population_id: 65540099
        cool_label: NewZealand
        description: NewZealand

    phenotype_mappings:
      LungCancer: [77]
      BreastCancer: [113]
      ColorectalCancer: [42, 48, 49]
      Leukemia: [226, 227, 232, 237]
      StomachCancer: [35]
      ProstateCancer: [151]
      BladderCancer: [163]
      LiverCancer: [58]
      OvarianCancer: [133]
      PancreaticCancer: [70]
      NonHodgkinLymphoma: [213]
      KidneyCancer: [160]
      ThyroidCancer: [200]
      CervicalCancer: [117]
      EsophagealCancer: [23]
      Melanoma: [100]
    column_mappings:
      gender_col: 0
      phenotype_col: 1
      age_col: 2
      cases_col: 3
      person_years_col: 4
    gender_mapping:
      male: 1
      female: 2
    
  
  ci5_x:
    type: "online"
    description: "Cancer Incidence in Five Continents X"
    url: "https://gco.iarc.fr/media/ci5/data/CI5-Xd.zip"
    cohort: "2003-2007"
    parser: "ci5_detailed_incidence_model"
    data_dir: "ci5_x"
    format: "zip"
    default_population: "38402499"
    has_header: false
    phenotype_mappings:
      LungCancer: [77]
      BreastCancer: [113]
      ColorectalCancer: [42, 48, 49]
      Leukemia: [226, 227, 232, 237]
      StomachCancer: [35]
      ProstateCancer: [151]
      BladderCancer: [163]
      LiverCancer: [58]
      OvarianCancer: [133]
      PancreaticCancer: [70]
      NonHodgkinLymphoma: [213]
      KidneyCancer: [160]
      ThyroidCancer: [200]
      CervicalCancer: [117]
      EsophagealCancer: [23]
      Melanoma: [100]
    column_mappings:
      gender_col: 0
      phenotype_col: 1
      age_col: 2
      cases_col: 3
      person_years_col: 4
    gender_mapping:
      male: 1
      female: 2
    age_structure:
      age_groups:
        - { min: 0, max: 4 }
        - { min: 5, max: 9 }
        - { min: 10, max: 14 }
        - { min: 15, max: 19 }
        - { min: 20, max: 24 }
        - { min: 25, max: 29 }
        - { min: 30, max: 34 }
        - { min: 35, max: 39 }
        - { min: 40, max: 44 }
        - { min: 45, max: 49 }
        - { min: 50, max: 54 }
        - { min: 55, max: 59 }
        - { min: 60, max: 64 }
        - { min: 65, max: 69 }
        - { min: 70, max: 74 }
        - { min: 75, max: 79 }
        - { min: 80, max: 84 }
        - { min: 85, max: null }  # open-ended age class
        - { min: null, max: null }  # class for unknown age
      unknown_age_class: 19
      open_ended_age_class: 18

  ci5_xi_summary:
    type: "online"
    description: "Cancer Incidence in Five Continents XI - summary"
    url: "https://gco.iarc.fr/media/ci5/data/ci5-xi/CI5-XI.zip"
    cohort: "2008-2012"
    parser: "ci5_summary_incidence_model"
    data_dir: "ci5_xi_summary"
    format: "zip"
    has_header: false
    phenotype_mappings:
      LungCancer: [21]
      BreastCancer: [29]
      ColorectalCancer: [13, 14]
      Leukemia: [56, 57, 58]
      StomachCancer: [11]
      ProstateCancer: [39]
      BladderCancer: [45]
      LiverCancer: [16]
      OvarianCancer: [35]
      PancreaticCancer: [18]
      NonHodgkinLymphoma: [53]
      KidneyCancer: [42]
      ThyroidCancer: [49]
      CervicalCancer: [32]
      EsophagealCancer: [10]
      Melanoma: [24]
    gender_mapping:
      male: 1
      female: 2
    age_structure:
      age_groups:
        - { min: 0, max: 4 }
        - { min: 5, max: 9 }
        - { min: 10, max: 14 }
        - { min: 15, max: 19 }
        - { min: 20, max: 24 }
        - { min: 25, max: 29 }
        - { min: 30, max: 34 }
        - { min: 35, max: 39 }
        - { min: 40, max: 44 }
        - { min: 45, max: 49 }
        - { min: 50, max: 54 }
        - { min: 55, max: 59 }
        - { min: 60, max: 64 }
        - { min: 65, max: 69 }
        - { min: 70, max: 74 }
        - { min: 75, max: 79 }
        - { min: 80, max: 84 }
        - { min: 85, max: null }  # open-ended age class
        - { min: null, max: null }  # class for unknown age
      unknown_age_class: 19
      open_ended_age_class: 18

  ci5_xi_detailed:
    type: "online"
    description: "Cancer Incidence in Five Continents XI - detailed (2008-2012)"
    url: "https://gco.iarc.fr/media/ci5/data/ci5-xi/CI5-XId.zip"
    cohort: "2008-2012"
    parser: "ci5_detailed_incidence_model"
    data_dir: "ci5_xi_detailed"
    format: "zip"
    default_population: "384002499"
    has_header: false
    phenotype_mappings:
      LungCancer: [71]
      BreastCancer: [111]
      ColorectalCancer: [37, 43, 44]
      Leukemia: [224, 229, 234]
      StomachCancer: [30]
      ProstateCancer: [147]
      BladderCancer: [165]
      LiverCancer: [53]
      OvarianCancer: [130]
      PancreaticCancer: [65]
      NonHodgkinLymphoma: [219]
      KidneyCancer: [162]
      ThyroidCancer: [200]
      CervicalCancer: [114]
      EsophagealCancer: [18]
      Melanoma: [93]
    column_mappings:
      gender_col: 0
      phenotype_col: 1
      age_col: 2
      cases_col: 3
      person_years_col: 4
    gender_mapping:
      male: 1
      female: 2
    age_structure:
      age_groups:
        - { min: 0, max: 4 }
        - { min: 5, max: 9 }
        - { min: 10, max: 14 }
        - { min: 15, max: 19 }
        - { min: 20, max: 24 }
        - { min: 25, max: 29 }
        - { min: 30, max: 34 }
        - { min: 35, max: 39 }
        - { min: 40, max: 44 }
        - { min: 45, max: 49 }
        - { min: 50, max: 54 }
        - { min: 55, max: 59 }
        - { min: 60, max: 64 }
        - { min: 65, max: 69 }
        - { min: 70, max: 74 }
        - { min: 75, max: 79 }
        - { min: 80, max: 84 }
        - { min: 85, max: null }  # open-ended age class
        - { min: null, max: null }  # class for unknown age
      unknown_age_class: 19
      open_ended_age_class: 18

  ci5_xii_summary:
    type: "online"
    description: "Cancer Incidence in Five Continents XII - summary"
    url: "https://gco.iarc.fr/media/ci5/data/vol12/Download/CI5-XII.zip"
    cohort: "2013-2017"
    parser: "ci5_parser"
    data_dir: "ci5_summary_incidence_model"
    format: "zip"
    has_header: false
    phenotype_mappings:
      LungCancer: [21]
      BreastCancer: [29]
      ColorectalCancer: [13, 14]
      Leukemia: [56, 57, 58]
      StomachCancer: [11]
      ProstateCancer: [39]
      BladderCancer: [45]
      LiverCancer: [16]
      OvarianCancer: [35]
      PancreaticCancer: [18]
      NonHodgkinLymphoma: [53]
      KidneyCancer: [42]
      ThyroidCancer: [49]
      CervicalCancer: [32]
      EsophagealCancer: [10]
      Melanoma: [24]
    gender_mapping:
      male: 1
      female: 2
    age_structure:
      age_groups:
        - { min: 0, max: 4 }
        - { min: 5, max: 9 }
        - { min: 10, max: 14 }
        - { min: 15, max: 19 }
        - { min: 20, max: 24 }
        - { min: 25, max: 29 }
        - { min: 30, max: 34 }
        - { min: 35, max: 39 }
        - { min: 40, max: 44 }
        - { min: 45, max: 49 }
        - { min: 50, max: 54 }
        - { min: 55, max: 59 }
        - { min: 60, max: 64 }
        - { min: 65, max: 69 }
        - { min: 70, max: 74 }
        - { min: 75, max: 79 }
        - { min: 80, max: 84 }
        - { min: 85, max: null }  # open-ended age class
        - { min: null, max: null }  # class for unknown age
      unknown_age_class: 19
      open_ended_age_class: 18

  ci5_xii_detailed:
    type: "online"
    description: "Cancer Incidence in Five Continents XII - detailed"
    url: "https://gco.iarc.fr/media/ci5/data/vol12/Download/CI5-XIId.zip"
    cohort: "2013-2017"
    parser: "ci5_detailed_incidence_model"
    data_dir: "ci5_xii_detailed"
    format: "zip"
    default_population: "384002499"
    has_header: false
    phenotype_mappings:
      LungCancer: [91]
      BreastCancer: [159]
      ColorectalCancer: [43, 53, 54]
      Leukemia: [274, 279, 284]
      StomachCancer: [33]
      ProstateCancer: [197]
      BladderCancer: [215]
      LiverCancer: [65]
      OvarianCancer: [178]
      PancreaticCancer: [80]
      NonHodgkinLymphoma: [269]
      KidneyCancer: [212]
      ThyroidCancer: [250]
      CervicalCancer: [162]
      EsophagealCancer: [21]
      Melanoma: [133]
    gender_mapping:
      male: 1
      female: 2
    column_mappings:
      gender_col: 0
      phenotype_col: 1
      age_col: 2
      cases_col: 3
      person_years_col: 4
    age_structure:
      age_groups:
        - { min: 0, max: 4 }
        - { min: 5, max: 9 }
        - { min: 10, max: 14 }
        - { min: 15, max: 19 }
        - { min: 20, max: 24 }
        - { min: 25, max: 29 }
        - { min: 30, max: 34 }
        - { min: 35, max: 39 }
        - { min: 40, max: 44 }
        - { min: 45, max: 49 }
        - { min: 50, max: 54 }
        - { min: 55, max: 59 }
        - { min: 60, max: 64 }
        - { min: 65, max: 69 }
        - { min: 70, max: 74 }
        - { min: 75, max: 79 }
        - { min: 80, max: 84 }
        - { min: 85, max: null }  # open-ended age class
        - { min: null, max: null }  # class for unknown age
      unknown_age_class: 19
      open_ended_age_class: 18
    static_test:
    type: "file"
    description: "Fixed incidences for testing purposes"
    data_dir: "tests"
    format: "zip"
    default_population: "i10"
    has_header: true
    phenotype_mappings:
      BreastCancer: 1
      OvarianCancer: 2
      PancreaticCancer: 3
      ProstateCancer: 4
    column_mappings:
      gender_col: 0
      phenotype_col: 1
      age_col: 2
      cases_col: 3
      person_years_col: 4
    gender_mapping:
      male: 1
      female: 2
    age_structure:
      age_groups:
        - { min: 0, max: 4 }
        - { min: 5, max: 9 }
        - { min: 10, max: 14 }
        - { min: 15, max: 19 }
        - { min: 20, max: 24 }
        - { min: 25, max: 29 }
        - { min: 30, max: 34 }
        - { min: 35, max: 39 }
        - { min: 40, max: 44 }
        - { min: 45, max: 49 }
        - { min: 50, max: 54 }
        - { min: 55, max: 59 }
        - { min: 60, max: 64 }
        - { min: 65, max: 69 }
        - { min: 70, max: 74 }
        - { min: 75, max: 79 }
        - { min: 80, max: 84 }
        - { min: 85, max: null }  # open-ended age class
        - { min: null, max: null }  # class for unknown age
      unknown_age_class: 19
      open_ended_age_class: 18

